export const products = [
  {
    product_name: 'iPhone 13 Pro',
    brand: 'Apple',
    category: 'Phone',
    price: 999,
    description: 'High-end smartphone with advanced camera features.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Samsung Galaxy S21',
    brand: 'Samsung',
    category: 'Phone',
    price: 799,
    description:
      'Flagship phone with powerful performance and vibrant display.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'MacBook Air (M2, 2023)',
    brand: 'Apple',
    category: 'Laptop',
    price: 1299,
    description: 'Ultra-slim laptop with M2 chip for enhanced performance.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Dell XPS 13',
    brand: 'Dell',
    category: 'Laptop',
    price: 1099,
    description:
      'Powerful laptop with InfinityEdge display for immersive viewing.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Google Pixel 6',
    brand: 'Google',
    category: 'Phone',
    price: 699,
    description: 'Smartphone with advanced AI features and exceptional camera.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'HP Spectre x360',
    brand: 'HP',
    category: 'Laptop',
    price: 1199,
    description:
      'Convertible laptop with stunning design and powerful performance.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'OnePlus 9 Pro',
    brand: 'OnePlus',
    category: 'Phone',
    price: 899,
    description: 'Flagship phone with Hasselblad camera partnership.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Microsoft Surface Laptop 4',
    brand: 'Microsoft',
    category: 'Laptop',
    price: 1299,
    description: 'Premium laptop with touchscreen and powerful performance.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'iPhone SE (2022)',
    brand: 'Apple',
    category: 'Phone',
    price: 399,
    description: 'Affordable iPhone with A15 Bionic chip.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Lenovo ThinkPad X1 Carbon',
    brand: 'Lenovo',
    category: 'Laptop',
    price: 1499,
    description:
      'Business laptop with durable build and impressive battery life.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Google Pixelbook Go',
    brand: 'Google',
    category: 'Laptop',
    price: 649,
    description: 'Ultralight Chromebook with long-lasting battery.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Samsung Galaxy Z Fold 3',
    brand: 'Samsung',
    category: 'Phone',
    price: 1799,
    description: 'Foldable smartphone with large AMOLED display.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'ASUS ROG Zephyrus G14',
    brand: 'ASUS',
    category: 'Laptop',
    price: 1499,
    description:
      'Gaming laptop with AMD Ryzen 9 processor and NVIDIA RTX 3060 graphics.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Sony Xperia 1 III',
    brand: 'Sony',
    category: 'Phone',
    price: 1299,
    description: 'Flagship phone with 4K OLED display and Zeiss optics.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Acer Swift 3',
    brand: 'Acer',
    category: 'Laptop',
    price: 699,
    description: 'Slim and lightweight laptop with AMD Ryzen 7 processor.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'OnePlus 9',
    brand: 'OnePlus',
    category: 'Phone',
    price: 729,
    description: 'High-performance phone with Hasselblad camera system.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'LG Gram 17',
    brand: 'LG',
    category: 'Laptop',
    price: 1499,
    description: 'Ultra-lightweight laptop with 17-inch display.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Motorola Edge+',
    brand: 'Motorola',
    category: 'Phone',
    price: 999,
    description: 'High-end phone with 108MP camera and 5G capability.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Lenovo Legion 5',
    brand: 'Lenovo',
    category: 'Laptop',
    price: 1099,
    description:
      'Gaming laptop with AMD Ryzen 7 processor and NVIDIA GTX 1660 Ti graphics.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Google Pixel 5a',
    brand: 'Google',
    category: 'Phone',
    price: 449,
    description: 'Mid-range phone with impressive camera capabilities.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Dell Inspiron 14',
    brand: 'Dell',
    category: 'Laptop',
    price: 649,
    description: 'Budget-friendly laptop with Intel Core i5 processor.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Sony Xperia 5 III',
    brand: 'Sony',
    category: 'Phone',
    price: 1099,
    description:
      'Compact phone with 120Hz OLED display and versatile camera setup.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'HP Envy x360',
    brand: 'HP',
    category: 'Laptop',
    price: 899,
    description:
      'Convertible laptop with AMD Ryzen 5 processor and Radeon graphics.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'OnePlus 8T',
    brand: 'OnePlus',
    category: 'Phone',
    price: 749,
    description: 'High-refresh-rate phone with fast charging technology.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Acer Aspire 5',
    brand: 'Acer',
    category: 'Laptop',
    price: 579,
    description:
      'Budget laptop with AMD Ryzen 5 processor and Full HD display.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Motorola Moto G Power (2022)',
    brand: 'Motorola',
    category: 'Phone',
    price: 249,
    description: 'Affordable phone with large battery capacity.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Microsoft Surface Pro 7',
    brand: 'Microsoft',
    category: 'Tablet',
    price: 799,
    description: 'Versatile 2-in-1 tablet with Intel Core i5 processor.',
    availability: 'In Stock',
    image: 'Image Link',
  },
  {
    product_name: 'Amazon Fire HD 10',
    brand: 'Amazon',
    category: 'Tablet',
    price: 149,
    description: 'Budget-friendly tablet with Full HD display.',
    availability: 'In Stock',
    image: 'Image Link',
  },
];
